[project]
name = "end-of-module-assignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alex Senger", email = "alex.senger@icloud.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
]

[project.scripts]
render-map = "end_of_module_assignment.render_map:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
